name: Ec2-deployment

on: 
  push:
    branches: 
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: code checkout
      uses: actions/checkout@v2
      
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install python3-pip
        sudo pip install flask
        sudo pip install pytest
  test:
    runs-on: ubuntu-latest
    steps:     
    
    - name: code checkout
      uses: actions/checkout@v2
      
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install python3-pip
        sudo pip install flask
        sudo pip install pytest
        
    - name: build and test
      run: |
        # testing scripts
        pytest test_app.py
    
    - name: pushing code to staging
      run: |
        # testcases are passed pushing code to staging
        #git checkout staging
        
  deploy:
    runs-on: ubuntu-latest
    steps:         
    - name: deployment step
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: | 
          git clone https://github.com/Sthatikonda8161/github_Actions.git
          sudo apt install -y python3-pip
          sudo pip install flask
          python3 github_Actions/app.py

          
